server:
  error:
    include-stacktrace: on_param

spring:
  application:
    name: springBoot
  datasource:
    url: jdbc:mysql://localhost:3306/Login?&createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus